#!/usr/bin/env bash
#
# deploy-rm2fb-conf.sh — Deploy rm2fb.conf and server to the reMarkable
#
# Usage:
#   ./scripts/deploy-rm2fb-conf.sh TABLET_IP UPDATE_ADDR CREATE_ADDR [SERVER_SO_PATH]
#
# Example:
#   ./scripts/deploy-rm2fb-conf.sh 10.11.99.1 0x3a1b2c 0x3a4d5e
#   ./scripts/deploy-rm2fb-conf.sh 10.11.99.1 0x3a1b2c 0x3a4d5e ./librm2fb_server.so.1.0.1
#
# This script:
#   1. Reads the firmware version from the tablet
#   2. Creates rm2fb.conf with your addresses
#   3. Deploys it to /etc/rm2fb.conf on the tablet
#   4. Optionally deploys the rm2fb server .so
#   5. Restarts xochitl with LD_PRELOAD
#
set -euo pipefail

if [ $# -lt 3 ]; then
    echo "Usage: $0 TABLET_IP UPDATE_ADDR CREATE_ADDR [SERVER_SO_PATH]"
    echo ""
    echo "  TABLET_IP     - IP of the reMarkable (default USB: 10.11.99.1)"
    echo "  UPDATE_ADDR   - Address of the 'update' function (e.g. 0x3a1b2c)"
    echo "  CREATE_ADDR   - Address of the 'create' function (e.g. 0x3a4d5e)"
    echo "  SERVER_SO_PATH - Optional: path to librm2fb_server.so to deploy"
    echo ""
    echo "Get the addresses by running: ./scripts/extract-rm2fb-addrs.sh"
    exit 1
fi

TABLET_IP="$1"
UPDATE_ADDR="$2"
CREATE_ADDR="$3"
SERVER_SO="${4:-}"
SSH_OPTS="-o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new"

echo "=== rm2fb Configuration Deployer ==="
echo ""

# Get firmware version
FIRMWARE_VER=$(ssh $SSH_OPTS "root@${TABLET_IP}" \
    'grep REMARKABLE_RELEASE_VERSION /usr/share/remarkable/update.conf 2>/dev/null | cut -d= -f2 || cat /etc/version 2>/dev/null || echo unknown' \
) || FIRMWARE_VER="unknown"
FIRMWARE_VER=$(echo "$FIRMWARE_VER" | tr -d '[:space:]')

echo "Firmware: $FIRMWARE_VER"
echo "update=$UPDATE_ADDR"
echo "create=$CREATE_ADDR"
echo ""

# Create rm2fb.conf
CONF_FILE=$(mktemp)
cat > "$CONF_FILE" <<EOF
# rm2fb configuration for firmware $FIRMWARE_VER
# Generated by deploy-rm2fb-conf.sh on $(date -u +"%Y-%m-%d")
# Addresses extracted from /usr/bin/xochitl

[$FIRMWARE_VER]
update=$UPDATE_ADDR
create=$CREATE_ADDR
EOF

echo "[1/3] Deploying rm2fb.conf..."
scp $SSH_OPTS "$CONF_FILE" "root@${TABLET_IP}:/etc/rm2fb.conf"
rm -f "$CONF_FILE"
echo "  -> /etc/rm2fb.conf deployed"

# Deploy server .so if provided
if [ -n "$SERVER_SO" ]; then
    echo ""
    echo "[2/3] Deploying rm2fb server library..."
    if [ ! -f "$SERVER_SO" ]; then
        echo "ERROR: Server .so not found: $SERVER_SO"
        exit 1
    fi
    ssh $SSH_OPTS "root@${TABLET_IP}" 'mkdir -p /opt/lib'
    scp $SSH_OPTS "$SERVER_SO" "root@${TABLET_IP}:/opt/lib/librm2fb_server.so.1.0.1"
    ssh $SSH_OPTS "root@${TABLET_IP}" 'cd /opt/lib && ln -sf librm2fb_server.so.1.0.1 librm2fb_server.so.1 && ln -sf librm2fb_server.so.1 librm2fb_server.so'
    echo "  -> /opt/lib/librm2fb_server.so deployed"
else
    echo ""
    echo "[2/3] No server .so provided — skipping"
    echo "  Make sure /opt/lib/librm2fb_server.so.1 exists on the tablet"
fi

# Check if server .so exists on tablet
echo ""
echo "[3/3] Verifying rm2fb server on tablet..."
HAS_SERVER=$(ssh $SSH_OPTS "root@${TABLET_IP}" 'ls /opt/lib/librm2fb_server.so* 2>/dev/null | head -1 || echo ""')
if [ -z "$HAS_SERVER" ]; then
    echo "WARNING: No rm2fb server library found on the tablet!"
    echo "  You need librm2fb_server.so from:"
    echo "  https://github.com/ddvk/remarkable2-framebuffer/releases"
    echo ""
    echo "  Note: Even with correct addresses in rm2fb.conf, you still"
    echo "  need the server .so. The .conf just tells it WHERE to hook."
    exit 1
fi
echo "  Found: $HAS_SERVER"

echo ""
echo "=== Ready to test ==="
echo ""
echo "To start xochitl with rm2fb:"
echo "  ssh root@${TABLET_IP}"
echo "  systemctl stop xochitl"
echo "  LD_PRELOAD=/opt/lib/librm2fb_server.so.1 xochitl &"
echo ""
echo "If xochitl starts normally (no crash, tablet UI appears), rm2fb is working."
echo "Then run remarkable-ssh — it will auto-detect the rm2fb backend."
echo ""
echo "If you see 'Missing address for function', the addresses may be wrong."
echo "If xochitl crashes, the addresses are wrong or the .so is ABI-incompatible."
echo ""
echo "To make it persistent across reboots, edit the systemd service:"
echo "  ssh root@${TABLET_IP}"
echo "  cat > /etc/systemd/system/xochitl.service.d/rm2fb.conf <<'UNIT'"
echo "  [Service]"
echo "  Environment=LD_PRELOAD=/opt/lib/librm2fb_server.so.1"
echo "  UNIT"
echo "  systemctl daemon-reload"
echo "  systemctl restart xochitl"
